List<Map<String, dynamic>> generateCustomNames() {
  return [
    {
      'title': 'FOSSIL',
      'subtitle': 'GRANT WATCH',
      'strap': 'LEATHER',
      'color': 'BROWN',
      'warranty': '1 Year',
      'price': '£299',
      'isFavourite': false,
    },
    {
      'title': 'TOMMY HILFIGER',
      'subtitle': 'DECKER WATCH',
      'strap': 'STAINLESS STEEL',
      'color': 'SILVER',
      'warranty': '2 YEARS',
      'price': '£499',
      'isFavourite': false,
    },
    {
      'title': 'ROLEX',
      'subtitle': 'SUBMARINER',
      'strap': 'OYESTER',
      'color': 'BLACK',
      'warranty': '5 YEARS',
      'price': '£999',
      'isFavourite': false,
    },
    {
      'title': 'TAG HEUER',
      'subtitle': 'CARRERA',
      'strap': 'RUBBER',
      'color': 'BLUE',
      'warranty': '3 YEARS',
      'price': '£1499',
      'isFavourite': false,
    },
    {
      'title': 'OMEGA',
      'subtitle': 'SEAMASTER',
      'strap': 'METAL',
      'color': 'SILVER',
      'warranty': '4 YEARS',
      'price': '£2999',
      'isFavourite': false,
    },
    {
      'title': 'CITIZEN',
      'subtitle': 'ECO-DRIVE',
      'strap': 'NYLON',
      'color': 'GREEN',
      'warranty': '2 YEARS',
      'price': '£199',
      'isFavourite': false,
    },
    {
      'title': 'SWATCH',
      'subtitle': 'ORIGINAL',
      'strap': 'PLASTIC',
      'color': 'RED',
      'warranty': '1 YEAR',
      'price': '£79',
      'isFavourite': false,
    },
    {
      'title': 'HAMILTON',
      'subtitle': 'KHAKI FIELD',
      'strap': 'LEATHER',
      'color': 'BLACK',
      'warranty': '3 YEARS',
      'price': '£599',
      'isFavourite': false,
    },
  ];
}
